### ISSUE TITLE
JSON:API format!

### ISSUE THREAD

**Issue by dcalixto** [pjungwir/active_model_serializers_pg#1]
Hello! thank you for the great work!
the gem is working flawlessly but i presume that on a association that is not formatted by JSON:API. 
is causing this issue! 
![json](https://user-images.githubusercontent.com/1009077/66725458-b7a98500-ee08-11e9-99c3-01aff1ab053c.png)

**Comment by pjungwir** [comment]
Thanks for trying out this gem! I don't see the error from your screenshot, which is just a bit of SQL. Did you get an error message? Or not the data you were expecting?

**Comment by dcalixto** [comment]
after turn on the gem show this sql message!
and in the controller:

def show
    render json: @post, status: 200
  end

```
{status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
exception: "#<ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column posts.post does not exist↵LINE 8: ...d', "posts"."id", 'slug', "posts"."slug", 'post', "posts"."p...↵                                                             ^↵: WITH↵t AS (↵  SELECT "posts".* FROM "posts" WHERE "posts"."id" = 3↵),↵t2 AS (↵  SELECT                     jsonb_build_object('id', "posts"."id"::text,↵                   'type', 'posts',↵                   'attributes', jsonb_build_object('title', "posts"."title", 'body', "posts"."body", 'user_id', "posts"."user_id", 'id', "posts"."id", 'slug', "posts"."slug", 'post', "posts"."post", 'username', "posts"."username")↵↵                   )↵         AS j↵  FROM    t AS "posts"↵  ↵),↵↵all_ctes AS (↵  SELECT  '{}'::jsonb AS j↵  WHERE   1=0↵  ↵),↵inc AS (↵  SELECT  COALESCE(jsonb_agg(j), '[]') AS j↵  FROM    all_ctes↵)↵			SELECT	jsonb_build_object('data', t2.j↵                           )↵FROM    t2↵CROSS JOIN  inc↵>"
status: 500
traces: {Application Trace: [{id: 61, trace: "app/controllers/posts_controller.rb:22:in `show'"}],…}
```

But if i change to  render json: { post: @post, status: 200 }
show no error!
So, need a root to render correctly?

**Comment by pjungwir** [comment]
Hi @dcalixto I see that you closed this issue, so does that mean you decided the problem was elsewhere? I would expect that `render json: @post, status: 200` would work correctly and not raise an error. But the error message suggests that you are trying to include something that isn't a database column (`column posts.post does not exist`). If that is an ordinary Ruby method then Postgres won't know about it, but you can `def self.post__sql` on the ActiveRecord class to include compatible SQL. Anyway, let me know if I can be of any help. :-)
