### ISSUE TITLE
Outside Rails!

### ISSUE THREAD

**Issue by dcalixto** [pjungwir/active_model_serializers_pg#2]
Hello @pjungwir, Instead of use rails generators i'd like use with sinatra, is just change this line require 'rails/generators/active_record'?

**Comment by pjungwir** [comment]
@dcalixto thanks for your interest in this gem! I didn't realize AMS worked outside of Rails, but I'm happy to try making this gem work in a Sinatra context too. Are you at least using ActiveRecord? I don't see a way around having that.

Generators shouldn't be required. I only use them to create a database migration to define a function to dasherize the contents of `json`/`jsonb` columns. Even that migration ought to be improved, because a `CREATE FUNCTION` won't show up in the `schema.rb`. On a real project I wound up skipping the migration and using [scenic](https://github.com/scenic-views/scenic) instead, but I'm reluctant to make that a strict dependency. I guess I could use it if it's there or just create the migration and print a warning otherwise. If you have any thoughts, let me know.

Anyway, assuming you don't mind defining that database function yourself, you're correct: you don't need to require the generators to use the gem.

**Comment by dcalixto** [comment]
@pjungwir my pleasure for your good work! and thank your for your reply, yes, i'm using ActiveRecord! https://github.com/sinatra-activerecord/sinatra-activerecord
Ok, soo, i'll try to create a no dependent rails version!
